-- Sound catalogue from WeakAuras_SharedMedia. Credits/licences: Media/SharedMedia/.
local _, Scan = ...
Scan.BundledAlertSounds = {
    { "HeartbeatSingle.ogg", "Heartbeat Single", 1 },
    { "BatmanPunch.ogg", "Batman Punch", 0.4 },
    { "BikeHorn.ogg", "Bike Horn", 0.8 },
    { "BoxingArenaSound.ogg", "Boxing Arena Gong", 1.8 },
    { "Bleat.ogg", "Bleat", 1.5 },
    { "CatMeow2.ogg", "Cat Meow", 1.2 },
    { "KittenMeow.ogg", "Kitten Meow", 0.6 },
    { "RobotBlip.ogg", "Robot Blip", 0.7 },
    { "SharpPunch.ogg", "Sharp Punch", 0.4 },
    { "WaterDrop.ogg", "Water Drop", 0.2 },
    { "AirHorn.ogg", "Air Horn", 1.9 },
    { "Applause.ogg", "Applause", 3 },
    { "BananaPeelSlip.ogg", "Banana Peel Slip", 0.6 },
    { "Blast.ogg", "Blast", 2.1 },
    { "CartoonVoiceBaritone.ogg", "Cartoon Voice Baritone", 2.1 },
    { "CartoonWalking.ogg", "Cartoon Walking", 1.2 },
    { "CowMooing.ogg", "Cow Mooing", 1.9 },
    { "RingingPhone.ogg", "Ringing Phone", 2.1 },
    { "RoaringLion.ogg", "Roaring Lion", 2.3 },
    { "Shotgun.ogg", "Shotgun", 0.6 },
    { "SquishFart.ogg", "Squish Fart", 0.3 },
    { "TempleBellHuge.ogg", "Temple Bell", 5.2 },
    { "Torch.ogg", "Torch", 2 },
    { "WarningSiren.ogg", "Warning Siren", 4.3 },
    { "554003", "Lich King Apocalypse", 10 },
    { "SheepBleat.ogg", "Sheep Blerping", 1.4 },
    { "RoosterChickenCalls.ogg", "Rooster Chicken Call", 3 },
    { "GoatBleating.ogg", "Goat Bleeting", 0.8 },
    { "AcousticGuitar.ogg", "Acoustic Guitar", 12 },
    { "SynthChord.ogg", "Synth Chord", 1.9 },
    { "ChickenAlarm.ogg", "Chicken Alarm", 1.2 },
    { "Xylophone.ogg", "Xylophone", 4.2 },
    { "Drums.ogg", "Drums", 0.6 },
    { "TadaFanfare.ogg", "Tada Fanfare", 1.7 },
    { "SqueakyToyShort.ogg", "Squeaky Toy Short", 1 },
    { "ErrorBeep.ogg", "Error Beep", 0.6 },
    { "OhNo.ogg", "Oh No", 1.6 },
    { "DoubleWhoosh.ogg", "Double Whoosh", 1 },
    { "Brass.mp3", "Brass", 6.1 },
    { "Glass.mp3", "Glass", 4.1 },
    { "Adds.ogg", "Voice: Adds", 1.1 },
    { "Boss.ogg", "Voice: Boss", 1 },
    { "Circle.ogg", "Voice: Circle", 1 },
    { "Cross.ogg", "Voice: Cross", 0.9 },
    { "Diamond.ogg", "Voice: Diamond", 0.9 },
    { "DontRelease.ogg", "Voice: Don't Release", 1.3 },
    { "Empowered.ogg", "Voice: Empowered", 1.4 },
    { "Focus.ogg", "Voice: Focus", 1.2 },
    { "Idiot.ogg", "Voice: Idiot", 0.9 },
    { "Left.ogg", "Voice: Left", 0.7 },
    { "Moon.ogg", "Voice: Moon", 0.9 },
    { "Next.ogg", "Voice: Next", 0.9 },
    { "Portal.ogg", "Voice: Portal", 1 },
    { "Protected.ogg", "Voice: Protected", 1.3 },
    { "Release.ogg", "Voice: Release", 1.1 },
    { "Right.ogg", "Voice: Right", 0.9 },
    { "RunAway.ogg", "Voice: Run Away", 1.3 },
    { "Skull.ogg", "Voice: Skull", 1 },
    { "Spread.ogg", "Voice: Spread", 1.4 },
    { "Square.ogg", "Voice: Square", 1.1 },
    { "Stack.ogg", "Voice: Stack", 1.2 },
    { "Star.ogg", "Voice: Star", 1 },
    { "Switch.ogg", "Voice: Switch", 1.3 },
    { "Taunt.ogg", "Voice: Taunt", 0.9 },
    { "Triangle.ogg", "Voice: Triangle", 1.1 },
    { "aggro.ogg", "Aggro", 0.5 },
    { "Arrow_swoosh.ogg", "Arrow Swoosh", 0.5 },
    { "bam.ogg", "Bam", 0.8 },
    { "bear_polar.ogg", "Polar Bear", 1.6 },
    { "bigkiss.ogg", "Big Kiss", 1.6 },
    { "BITE.ogg", "Bite", 0.3 },
    { "burp4.ogg", "Burp", 2.5 },
    { "cat2.ogg", "Cat", 1.1 },
    { "chant2.ogg", "Chant Major 2nd", 4.2 },
    { "chant4.ogg", "Chant Minor 3rd", 5.1 },
    { "chimes.ogg", "Chimes", 6.8 },
    { "cookie.ogg", "Cookie Monster", 9.5 },
    { "ESPARK1.ogg", "Electrical Spark", 1.6 },
    { "Fireball.ogg", "Fireball", 1.8 },
    { "Gasp.ogg", "Gasp", 0.6 },
    { "heartbeat.ogg", "Heartbeat", 4.5 },
    { "hic3.ogg", "Hiccup", 0.4 },
    { "huh_1.ogg", "Huh?", 0.5 },
    { "hurricane.ogg", "Hurricane", 4.6 },
    { "hyena.ogg", "Hyena", 2.1 },
    { "kaching.ogg", "Kaching", 1.3 },
    { "moan.ogg", "Moan", 2.7 },
    { "panther1.ogg", "Panther", 1.3 },
    { "phone.ogg", "Phone", 3.1 },
    { "PUNCH.ogg", "Punch", 0.4 },
    { "rainroof.ogg", "Rain", 4.8 },
    { "rocket.ogg", "Rocket", 4.2 },
    { "shipswhistle.ogg", "Ship's Whistle", 3.6 },
    { "shot.ogg", "Gunshot", 2.3 },
    { "snakeatt.ogg", "Snake Attack", 1.4 },
    { "sneeze.ogg", "Sneeze", 1.5 },
    { "sonar.ogg", "Sonar", 2.3 },
    { "splash.ogg", "Splash", 2.2 },
    { "Squeakypig.ogg", "Squeaky Toy", 6.4 },
    { "swordecho.ogg", "Sword Ring", 1.4 },
    { "throwknife.ogg", "Throwing Knife", 0.8 },
    { "thunder.ogg", "Thunder", 3.4 },
    { "wickedmalelaugh1.ogg", "Wicked Male Laugh", 3.6 },
    { "wilhelm.ogg", "Wilhelm Scream", 1.3 },
    { "wlaugh.ogg", "Wicked Female Laugh", 3.1 },
    { "wolf5.ogg", "Wolf Howl", 2 },
    { "yeehaw.ogg", "Yeehaw", 2.5 },
}
