-- Builds ProfitHub/Core/DB/SpecStats_MID.lua from CraftSim's specialization
-- data (which specialization nodes and perks affect each recipe, and what
-- stats they give). CraftSim is MIT-licensed; see LICENSE-CraftSim.txt.
--
-- Run from the addon root after CraftSim was updated for a new patch:
--   lua5.1 scripts/ImportCraftSimSpecData.lua "<AddOns>/CraftSim" [output file]
local source = arg[1]
local output = arg[2] or 'ProfitHub/Core/DB/SpecStats_MID.lua'
assert(source, 'usage: lua ImportCraftSimSpecData.lua <path to CraftSim> [output file]')

local PROFESSIONS = { 'Alchemy', 'Blacksmithing', 'Enchanting', 'Engineering', 'Inscription', 'Jewelcrafting',
    'Leatherworking', 'Tailoring' }
-- The stats HironCraft shows; the rest of CraftSim's keys are bookkeeping.
local STATS = { 'skill', 'multicraft', 'resourcefulness', 'ingenuity', 'craftingspeed',
    'additionalitemscraftedwithmulticraft', 'reagentssavedfromresourcefulness', 'reduceconcentrationcost',
    'ingenuityrefundincrease' }

local version = '?'
do
    local toc = io.open(source .. '/CraftSim.toc', 'r')
    if toc then
        version = toc:read('*a'):match('## Version:%s*([%w%.%-]+)') or version
        toc:close()
    end
end

local CraftSim = { SPECIALIZATION_DATA = { MIDNIGHT = {} } }
local nodes, recipes = {}, {}
for _, name in ipairs(PROFESSIONS) do
    local chunk = assert(loadfile(source .. '/Data/SpecializationData/Midnight/' .. name .. '.lua'))
    chunk('CraftSim', CraftSim)
    local data = assert(CraftSim.SPECIALIZATION_DATA.MIDNIGHT[name:upper() .. '_DATA'], name .. ': no data')
    for id, node in pairs(data.nodeData) do
        assert(not nodes[id] or nodes[id].nodeID == node.nodeID, 'node ' .. id .. ' differs between professions')
        nodes[id] = node
    end
    for recipeID, list in pairs(data.recipeMapping) do
        -- A recipe two professions share gets both lists: the nodes of the
        -- profession that is not open are simply not found in the game.
        local merged = recipes[recipeID] or {}
        for _, id in ipairs(list) do merged[#merged + 1] = id end
        recipes[recipeID] = merged
    end
end

local lines = {
    '-- Generated by scripts/ImportCraftSimSpecData.lua from CraftSim ' .. version .. '. Do not edit: run the script again.',
    '-- Data (c) 2023 Florian Schneider, MIT License; see LICENSE-CraftSim.txt.',
    '--',
    '-- N[id] = { base node, max rank, stats } for a specialization node (id == base node: the stats are per',
    '-- rank) or for one of its perks (the stats are gained at the perk\'s rank). I[node] = icon.',
    '-- R[recipe] = the nodes that affect it, then those of their perks that give it stats.',
    'local PT = HironCraftProfit',
    'if not PT then return end',
    'PT.SpecStats = PT.SpecStats or { nodes = {}, recipes = {}, icons = {} }',
    'PT.SpecStats.source = "CraftSim ' .. version .. '"',
    'local N, R, I = PT.SpecStats.nodes, PT.SpecStats.recipes, PT.SpecStats.icons',
}

local ids = {}
for id in pairs(nodes) do ids[#ids + 1] = id end
table.sort(ids)
local kept = {}
for _, id in ipairs(ids) do
    local node = nodes[id]
    local parts = {}
    for _, stat in ipairs(STATS) do
        local value = node.stats and tonumber(node.stats[stat])
        if value and value ~= 0 then parts[#parts + 1] = stat .. '=' .. tostring(value) end
    end
    -- A base node is kept even without stats of its own: its perks hang on it.
    if #parts > 0 or node.base then
        kept[id] = true
        lines[#lines + 1] = string.format('N[%d]={%d,%d,{%s}}', id, node.nodeID, node.maxRank, table.concat(parts, ','))
        if node.base and node.icon then lines[#lines + 1] = string.format('I[%d]=%d', id, node.icon) end
    end
end

-- Many recipes share one list of nodes: each list is written once.
local byList, order = {}, {}
local recipeIDs = {}
for recipeID in pairs(recipes) do recipeIDs[#recipeIDs + 1] = recipeID end
table.sort(recipeIDs)
for _, recipeID in ipairs(recipeIDs) do
    -- As CraftSim counts it: a recipe lists perks, and a node affects the
    -- recipe (with its stats per rank) when any of its perks is listed, also
    -- one without stats of its own. So the nodes are worked out here.
    local list, perks, seen = {}, {}, {}
    for _, id in ipairs(recipes[recipeID]) do
        local node = assert(nodes[id], 'recipe ' .. recipeID .. ' lists ' .. id .. ', which has no data')
        if node.maxRank == 1 and not seen[id] then
            seen[id] = true
            assert(id ~= node.nodeID, 'node ' .. id .. ' has one rank')
            if not seen[node.nodeID] then
                seen[node.nodeID] = true
                if kept[node.nodeID] then list[#list + 1] = node.nodeID end
            end
            if kept[id] then perks[#perks + 1] = id end
        end
    end
    for _, id in ipairs(perks) do list[#list + 1] = id end
    local key = table.concat(list, ',')
    if not byList[key] then
        byList[key] = {}
        order[#order + 1] = key
    end
    table.insert(byList[key], recipeID)
end
lines[#lines + 1] = 'local function Share(list, recipes) for _, recipe in ipairs(recipes) do R[recipe] = list end end'
for _, key in ipairs(order) do
    lines[#lines + 1] = string.format('Share({%s},{%s})', key, table.concat(byList[key], ','))
end

local file = assert(io.open(output, 'wb'))
file:write(table.concat(lines, '\n'), '\n')
file:close()
print(string.format('%s: %d nodes and perks, %d recipes in %d lists, from CraftSim %s', output, #ids, #recipeIDs, #order, version))
